services:
  database:
    image: 'postgres:15.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=graffos'
      - 'POSTGRES_DB=graffos'
      - 'POSTGRES_PASSWORD=graffosPassword2024'