spring:
  jpa:
    hibernate:
      ddl-auto: create
  debug: true
  application:
    name: Random Utils
  thymeleaf:
    cache: false
  datasource:
    random:
      url: jdbc:postgresql://localhost:15432/graffos?createDatabaseIfNotExist=true
      username: graffos
      password: graffosPassword2024
    teamconnect636:
      url: jdbc:sqlserver://localhost:1433;databaseName=teamconnect_636;Encrypt=true;TrustServerCertificate=true
      username: teamconnect
      password: password
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      show-sql: true
      dialect: org.hibernate.dialect.SQLServer2012Dialect
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

server:
  port : 3333